name: Build

on:
  workflow_dispatch:
  push:
    branches: ['**']
    tags: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v2
      - run: ./gradlew --no-daemon assemble
      - uses: actions/upload-artifact@v3
        with:
          name: apks
          path: app/build/outputs/apk/
